version: '3.8'

services:
  magic_predictor:
    build: .
    container_name: magic_predictor_service
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./assets:/app/assets
    